import { usePrivy, useWallets, getAccessToken } from "@privy-io/react-auth";
import { privyEnabled } from "./PrivyGate";

/**
 * A single, safe view of the player's account.
 *
 * Privy's hooks throw if called outside a PrivyProvider, and the provider is
 * absent when no app id is configured — so everything here is guarded and
 * degrades to "guest" rather than crashing the app.
 */

export interface Account {
  ready: boolean;
  authenticated: boolean;
  login: () => void;
  logout: () => void;
  email: string | null;
  /** Address of the wallet Privy created, or the first linked one. */
  address: string | null;
  /** True when the wallet was generated by Privy rather than connected. */
  isEmbedded: boolean;
  available: boolean;
}

export function useAccount(): Account {
  if (!privyEnabled) return GUEST;

  // Safe: privyEnabled is constant for the lifetime of the app, so this branch
  // never changes between renders and hook order stays stable.
  /* eslint-disable react-hooks/rules-of-hooks */
  const { ready, authenticated, login, logout, user } = usePrivy();
  const { wallets } = useWallets();
  /* eslint-enable react-hooks/rules-of-hooks */

  /**
   * An external wallet wins over the embedded one.
   *
   * This used to be `embedded ?? wallets[0]`, which showed the player the empty
   * wallet Privy generated instead of the one holding their tokens. The server
   * no longer takes holdings from here at all — it reads wallets proved to it by
   * signature — but the address shown in the UI should still be the one that
   * means something to the player.
   */
  const embedded = wallets.find((w) => w.walletClientType === "privy");
  const external = wallets.find((w) => w.walletClientType !== "privy");
  const wallet = external ?? embedded;

  return {
    ready,
    authenticated,
    login,
    logout,
    email: (user?.email?.address as string | undefined) ?? null,
    address: wallet?.address ?? null,
    isEmbedded: Boolean(embedded),
    available: true,
  };
}

const GUEST: Account = {
  ready: true,
  authenticated: false,
  login: () => {},
  logout: () => {},
  email: null,
  address: null,
  isEmbedded: false,
  available: false,
};

/**
 * The access token to hand the game server, which verifies it before trusting
 * any identity claim. Returns null when logged out or Privy isn't configured.
 */
export async function accountToken(): Promise<string | null> {
  if (!privyEnabled) return null;
  try {
    return (await getAccessToken()) ?? null;
  } catch {
    return null;
  }
}

/** A short, human-readable label for the signed-in account. */
export function accountLabel(account: Account): string {
  if (account.email) return account.email.split("@")[0];
  if (account.address) return `${account.address.slice(0, 6)}…${account.address.slice(-4)}`;
  return "Guest";
}
