/**
 * External links.
 *
 * PLACEHOLDERS — replace these three values before going public. Everything on
 * the site reads from here, so there is exactly one place to edit.
 *
 * Any link left as "#" renders as a disabled, non-clickable chip rather than a
 * dead link, so a half-configured site never ships a broken anchor.
 */
export const LINKS = {
  x: "#",
  telegram: "#",
  discord: "#",

  /**
   * The Residents collection on the marketplace.
   *
   * Live, unlike the three above. The in-game collection panel has always
   * pointed here; this is the same destination for the public site, read from
   * the same constant so the two can never drift apart.
   */
  opensea: "https://opensea.io/collection/quanto-residents",

  /**
   * The whitepaper PDF. Generated by `npm run whitepaper` into public/, so it
   * is served as a static file and opens in the browser's own PDF viewer.
   * Point this at a CDN or IPFS URL instead if you'd rather host it elsewhere.
   */
  whitepaperPdf: "/whitepaper.pdf",
} as const;

export function isConfigured(url: string) {
  return Boolean(url) && url !== "#";
}
